spark.driver.port ${SPARK_DRIVER_PORT}
spark.fileserver.port ${SPARK_FILESERVER_PORT}
spark.broadcast.port ${SPARK_BROADCAST_PORT}
spark.replClassServer.port ${SPARK_REPLCLASSSERVER_PORT} 
spark.blockManager.port ${SPARK_BLOCKMANAGER_PORT}
spark.executor.port ${SPARK_EXECUTOR_PORT}
spark.ui.port ${SPARK_UI_PORT}
spark.master.rest.port ${SPARK_MASTER_REST_PORT}
spark.broadcast.factory org.apache.spark.broadcast.HttpBroadcastFactory
spark.eventLog.enabled true
spark.eventLog.dir ${SPARK_HOME}/logs
spark.history.fs.logDirectory ${SPARK_HOME}/logs
